# Generated by Django 5.2.5 on 2025-08-30 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlar'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year'], 'verbose_name': 'Mashina', 'verbose_name_plural': 'Mashinalar'},
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Rasmi'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Sotuvda bormi?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Mamlakat'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brend nomi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='salon.brand', verbose_name='Brendi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mashina nomi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Yili'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Muallif')),
                ('text', models.TextField(verbose_name='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='salon.car', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
